### PR TITLE
Add EVE Station Trading Assistant

### PR DESCRIPTION
**Pull request by ignitedPotato**
Please add the new EVE Station Trading Assistant (ESTA)

### CODE REVIEW

**Comment by cvweiss** [comment]
Couple questions for you:

* Is there a download link?
* How are you supposed to use it? I don't see anyway to interact with the page.

You might have users asking you these questions :)

**Comment by ignitedPotato** [comment]
I don't really understand your questions. Did you visit the page? You can click on the ship images.

**Comment by cvweiss** [comment]
Right, you have nothing that says click the images for further interaction. You mention lists, but none are to be seen on that page.

Try to see it from a stupid user perspective. Just trying to help. Looks nice though.

**Comment by ignitedPotato** [comment]
I get your point. I will improve the introduction a bit. Thanks for your feedback.

**Pull request merged**
