### PR TITLE
Add Space Markets tool

### PR DESCRIPTION
**Pull request by apseren**

### CODE REVIEW

**Comment by cvweiss** [comment]
Rather than linking to a file, can you link to a page that describes what the tool is? It does open to a page but it is a modal, this feels like an advertisement.

What proof do users have against trojans/viruses from the EXE file? Is this tool open source?

**Comment by apseren** [comment]
Currently, it doesn't have an official website, just the store page. I'm the creator of this tool.

It's not open source. Overwolf apps are essentially web apps packaged inside an installer binary, the app specific code is readable after extracted, although the code has been minified. The source of the plugin used for io is here: https://github.com/apseren/overwolf-plugins

If you don't want to add it to the list, no problem, I can close the pull request if you want. But the README.md should be more clear about the criteria to accept new apps.

**Comment by cvweiss** [comment]
Please leave open as this looks like a very nice & useful tool.

I'm going to hold off on merging until I get some confirmation that the binary is safe.

>  But the README.md should be more clear about the criteria to accept new apps.

I believe you're the first to add a brand-new-binary since the inception of this list. Existing binaries already had a long history established.  You may be right in that some clarification may be needed.

**Comment by soratidus999** [comment]
I am uncomfortable with this.

Yes, the risks that exist with a binary of this nature exist with any. Multiplied by any binary that can self update, creating attack vectors that didnt exist before etc.

Obfusticate this further behind overwolf, and this creates far too many opportunities for malicious code to be distributed without even a users informed consent.

EVE might be one of the only games where this is even a consideration, but im extremely wary nonetheless.

**Comment by fuzzysteve** [comment]
I have to agree I'm afraid. To be clear, it's nothing personal. But downloadable programs, without existing form, make me wary.

**Comment by cvweiss** [comment]
With these comments I'm going to close this PR.

fwiw, a website would be perfect for this type of tool.

**Comment by GoldenGnu** [comment]
> Your product should be user friendly and beyond "beta" stages.

That is from the readme file, you only released one version, so far, regardless if it's a beta or not.

Trust is the hardest thing to earn in eve, making people download and execute code on there machines requires a lot of trust.
There are ways to earn trust, like going open source.
Another would being something like https://www.virustotal.com

According to overwolf, they do curate the software for download there (so that is a start):
https://www.overwolf.com/our-commitment/

**Pull request closed without merging**
