### PR TITLE
add ESI knife

### PR DESCRIPTION
**Pull request by a-tal**
not sure if you like this in misc or would rather see a new heading for `recruitment` or something instead... lmk

### CODE REVIEW

**Comment by andimiller** [comment]
a `recruitment` or `HR` section would make sense to me

**Comment by cvweiss** [comment]
Agreed, perhaps a new section, Services, and then a subsection, Recruitment, would work. Thoughts?

**Comment by andimiller** [comment]
a lot of the existing entries are services, that might want a major re-sort of the list, especially if you also want a `Services which can be Self-Hosted` section

**Comment by a-tal** [comment]
roger, submitted as its own section for now. agreed that we could probably present this info slightly better though, probably best left to its own PR

**Pull request merged**
