### PR TITLE
Add link for ESI proxy

### PR DESCRIPTION
**Pull request by deadlybulb**

### CODE REVIEW

**Comment by cvweiss** [comment]
I think this is an awesome idea and quite innovative too. Before I accept the PR I want to double check with a couple of CCP devs to make sure it isn't violating the EULA in any way.

@fuzzysteve what do you think? I think it is probably fine, but it might be better to ask.

**Comment by cvweiss** [comment]
@deadlybulb Here is the feedback I've gotten:

> ccp_bartender [10:28] 
> @squizz our general stance on re-serving EVE API data under the terms of the Developer Agreement is that one is /usually/ welcome to do so, but one is completely and totally responsible for downstream use of that data under the terms of the developer agreement. If someone uses a service offered in this way to scam, we would hold the service provider responsible.

Are you still interested in making this public on this list since you will be liable?

**Comment by deadlybulb** [comment]
If I understand this correctly, I'm liable if I scam someone, but then so is anyone who runs any sort of service that asks for scope authorization (and does something evil with the data).  An interesting question is whether I'm liable if someone "steals" one of the key/hash pairs I provide and then does some evil with that.  That's not really under my control.

Let me clarify this one point with bartender.  Regardless, I'd still probably want to post the link to the software, but tell users they need to run their own instance if they want to use it (less convenient, but probably necessary if I'm supposed to be liable).

**Comment by cvweiss** [comment]
I believe he is saying that you are liable since it passes through your site since you provide the service. Which kind of sucks for you if someone decides to use your service for something nefarious.

**Comment by deadlybulb** [comment]
If the interpretation is that broad, then I'll move the link to the "library" section and others can download and run their own proxies if they need to.

**Comment by tsuthers-ccpgames** [comment]
Ultimately, we have an agreement with you, not necessarily your customers. Additionally, any wrongdoing detected on our end will arrive stamped with your client ID.

Under such circumstances, we would have no way to validate the providence of any logs provided by you to demonstrate that you are not the source of the wrongdoing (using your own service as cover). Thus, we would have to proceed with the assumption that you are responsible for any malicious traffic origination from your service, a standard approach when dealing with services on the internet that are behaving maliciously*.

My recommendations are that you /either/ vet your customers extremely carefully, so that you have a high degree of confidence in them, /or/ package your app such that others can acquire and assign their own client ID and secret to it, and run their own server. Possibly both.

*otherwise know as the "that's not my problem, fix your shit" approach 😛

**Comment by deadlybulb** [comment]
Ack.  So I'll close the service off to anyone except me or anyone else I'm willing to vet, and I'll change this PR to reference the github project and move it to the libraries section.  Thanks everyone!

**Comment by deadlybulb** [comment]
Moved to the libraries section.  I'm comfortable adding this to the list in its present form.  Thanks!

**Pull request merged**
