### PR TITLE
Add in GalaxyFinder to Wormhole Tools

### PR DESCRIPTION
**Pull request by w9jds**

### CODE REVIEW

**Comment by cvweiss** [comment]
I've gone ahead and added it. As a user, I did try to use your site and found it extremely frustrating. I had to authenticate multiple times, tell the site to register me after already authenticating, and then I finally get to a screen where I see a cropped version of my character's picture and I can't seem to do anything from there.

I think you need to work on this a bit :)

**Comment by w9jds** [comment]
Hmm, yeah so the registration is a bit unique. I basically take you to an account management system. There it only wants your roles and titles scopes. Then when you to go to the mapper it requires additional scopes so it has you add those to the list. I created an account system that adds scopes based on what scopes my apps require. This way when an app adds or uses scopes you don't have it will automatically revoke the old token, amend the scopes needed and request a new one. This way all my tools use the accounting system, and you only require scopes needed for the tools that you currently use.

When you say you got to a screen with a cropped version, what do you mean by that?

**Comment by cvweiss** [comment]
Nothing was coming up. I've since gone back and I see content now and the mapper.

**Comment by w9jds** [comment]
Hmm interesting. Haven't heard this report, but I'll take a look. I'll also see if I can better streamline the login process, I know it has caused confusion in the past.

**Pull request merged**
