### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by evrial**

### CODE REVIEW

**Comment by cvweiss** [comment]
Rejecting this. Too much removed without viable replacements and no reasoning given why.

Keep in mind this isn't just for players but for developers as well.

**Comment by evrial** [comment]
If you notice removed only EFT, osmium, eve-kill and battleclinic which are abandoned or dead.

**Comment by cvweiss** [comment]
EFT I marked as pending removal, I'm giving them to May to become active again. Osmium appears to still be alive and well, can you show me how its dead? Battleclinic was left there for a reason and it even says why, the eve-kill link redirects to Karbowiak's new killboard, which is fine the text probably just needs to be changed.

You also removed killboard utilities, which are used. As well as the SSO section for developers.

**Comment by evrial** [comment]
Your response if biased toward your personal preferences. EFT is 10 months outdated, osmium is Version 0.13.5, released 2015-08-25, and have you checked eve-kill link? Removed only two redundant section headers which are libraries in fact.

**Comment by cvweiss** [comment]
> Your response is biased toward your personal preferences.

Of course it is. As for EFT, I see no problem with leaving it as pending removal. If Osmium hasn't been updated since 2015, then that needs to go, please create a separate PR for just that.

I stand by my choice for leaving the eve-kill link since it redirects. You don't have to agree with me.

Not all of your changes are bad. However, it was a wide sweeping change with no notes attached.

**Pull request closed without merging**
